apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-compactor
  namespace: monitoring
  labels:
    release: prom-op
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http
    interval: 30s
  selector:
    matchLabels:
      app: thanos-compactor
